# Generated by Django 4.2.30 on 2026-06-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='rented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
