# Generated by Django 4.2.30 on 2026-06-07 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(upload_to='documents/citizenship/')),
                ('citizenship_back', models.ImageField(upload_to='documents/citizenship/')),
                ('lalpurja', models.ImageField(upload_to='documents/lalpurja/')),
                ('selfie_image', models.ImageField(upload_to='documents/selfie/')),
                ('ocr_extracted_name', models.CharField(blank=True, max_length=200)),
                ('ocr_citizenship_number', models.CharField(blank=True, max_length=100)),
                ('ocr_address', models.CharField(blank=True, max_length=300)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
