# Generated by Django 4.2.30 on 2026-06-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField(blank=True)),
                ('position', models.CharField(choices=[('homepage_top', 'Homepage Top Banner'), ('homepage_between', 'Homepage Between Cards'), ('listing_detail', 'Listing Detail Below Images'), ('phone_reveal', 'Phone Reveal Rewarded Ad')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRevealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveal_logs', to='listings.listing')),
            ],
        ),
    ]
