# Generated by Django 4.2.30 on 2026-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text="Ad won't show after this date. Leave blank to run indefinitely.", null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text="Ad won't show before this date. Leave blank to start immediately.", null=True),
        ),
    ]
